### ISSUE TITLE
Building bdist for linux exit on script for windows not found

### ISSUE THREAD

**Issue by edoput** [digitalfox/pysql#6]
I can't install the package without getting an error from the process.

I tried building the package locally and got this log [log.txt](https://github.com/digitalfox/pysql/files/1667333/log.txt).

Running `python setup.py build --format=wininst` doesn't have any problem but `python setup.py build` exits with an error.

**Comment by digitalfox** [comment]
Please use python3 not python 2.7 for that. If you prefer to stick witch python 2, then you should checkout an older release of pysql (like ae8fdc3cf4d0c78973f7795b1964a4d8a5ff6811), not master.

**Comment by edoput** [comment]
I'm using the latest version published on pypi but with python3 it won't even install becuase it hasn't been updated in a while

```python
Collecting pysql
  Using cached pysql-0.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u4lisw75/pysql/setup.py", line 31
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u4lisw75/pysql/
```

Using the master branch with pip and python3 holds the same result of not finding the windows install script

```
 Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-r360fd75-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"
install --record /tmp/pip-ich465ob-record/install-record.txt --single-version-externally-managed --compile: Warning, cannot read version file (name 'file' is not defined)
Defaulting to 'snapshot' running install running build running build_py creating build creating build/lib creating build/lib/pysql copying src/pysql/pysqlshell.py -> build/lib/pysql
copying src/pysql/pysqlaudit.py -> build/lib/pysql
copying src/pysql/pysqldb.py -> build/lib/pysql
copying src/pysql/pysqloptionparser.py -> build/lib/pysql
copying src/pysql/pysqlcomplete.py -> build/lib/pysql
copying src/pysql/__init__.py -> build/lib/pysql
copying src/pysql/pysqlconf.py -> build/lib/pysql
copying src/pysql/pysqlmain.py -> build/lib/pysql
copying src/pysql/pysqlgraphics.py -> build/lib/pysql
copying src/pysql/pysqloraobjects.py -> build/lib/pysql
copying src/pysql/pysqlqueries.py -> build/lib/pysql
copying src/pysql/pysqlhelpers.py -> build/lib/pysql
copying src/pysql/pysqlfunctions.py -> build/lib/pysql
copying src/pysql/pysqlexception.py -> build/lib/pysql
copying src/pysql/pysqlcolor.py -> build/lib/pysql
running build_scripts creating build/scripts-3.4
copying and adjusting src/bin/pysql -> build/scripts-3.4
changing mode of build/scripts-3.4/pysql from 644 to 755
running install_lib creating /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlshell.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlaudit.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqldb.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqloptionparser.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlcomplete.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/__init__.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlconf.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlmain.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlgraphics.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqloraobjects.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlqueries.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlhelpers.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlfunctions.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlexception.py -> /usr/local/lib/python3.4/dist-packages/pysql
copying build/lib/pysql/pysqlcolor.py -> /usr/local/lib/python3.4/dist-packages/pysql
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlshell.py to pysqlshell.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlaudit.py to pysqlaudit.cpython-34.pyc byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqldb.py to pysqldb.cpython-34.pyc byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloptionparser.py to pysqloptionparser.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcomplete.py to pysqlcomplete.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/__init__.py to __init__.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlconf.py to pysqlconf.cpython-34.pyc byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlmain.py to pysqlmain.cpython-34.pyc byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlgraphics.py to pysqlgraphics.cpython-34.pyc byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloraobjects.py to pysqloraobjects.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlqueries.py to pysqlqueries.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlhelpers.py to pysqlhelpers.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlfunctions.py to pysqlfunctions.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlexception.py to pysqlexception.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcolor.py to pysqlcolor.cpython-34.pyc 
writing byte-compilation script '/tmp/tmpdmn95jg1.py' /usr/bin/python3 -O /tmp/tmpdmn95jg1.py removing /tmp/tmpdmn95jg1.py
running install_data creating /usr/local/share/locale
creating /usr/local/share/locale/fr
creating /usr/local/share/locale/fr/LC_MESSAGES
copying src/share/locale/fr/LC_MESSAGES/pysql.mo -> /usr/local/share/locale/fr/LC_MESSAGES/ creating /usr/local/share/pysql copying version -> /usr/local/share/pysql
copying README -> /usr/local/share/pysql
copying ChangeLog -> /usr/local/share/pysql
copying ChangeLog-Synthesis -> /usr/local/share/pysql
copying LICENSE -> /usr/local/share/pysql
running install_egg_info running egg_info
creating pysql.egg-info
writing top-level names to pysql.egg-info/top_level.txt
writing dependency_links to pysql.egg-info/dependency_links.txt 
writing pysql.egg-info/PKG-INFO
writing manifest file 'pysql.egg-info/SOURCES.txt' warning: manifest_maker: standard file '-c' not found reading manifest file 'pysql.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pysql.egg-info/SOURCES.txt'
Copying pysql.egg-info to /usr/local/lib/python3.4/dist-packages/pysql-snaphot.egg-info \
running install_scripts copying build/scripts-3.4/pysql -> /usr/local/bin
changing mode of /usr/local/bin/pysql to 755
error: install_script 'pysql_w32_postinst.py' not found in scripts
```

**Comment by digitalfox** [comment]
Indeed, only master is on python 3 and no release has been done so far. 

Could you please provide the command line you use for the package ? Here, python3 setup.py bdist
do the job (with python 3.4.6).

**Comment by edoput** [comment]
Hi Sébastien, thank you for your help with this. I'm sorry I haven't been able to respond you early.

The command is `pip3 install https://github.com/digitalfox/pysql/tarball/master` and the output is
 
```
/usr/bin/pip3 run on Tue Feb 13 10:02:16 2018
Downloading/unpacking https://github.com/digitalfox/pysql/tarball/master
  Downloading from URL https://github.com/digitalfox/pysql/tarball/master
  Running setup.py (path:/tmp/pip-_yvnmoc2-build/setup.py) egg_info for package from https://github.com/digitalfox/pysql/tarball/master
    Warning, cannot read version file (name 'file' is not defined)
    Defaulting to 'snapshot'
    running egg_info
    creating pip-egg-info/pysql.egg-info
    writing pip-egg-info/pysql.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pysql.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/pysql.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pysql.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/pysql.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/pysql.egg-info/SOURCES.txt'
  Source in /tmp/pip-_yvnmoc2-build has version snaphot, which satisfies requirement pysql==snaphot from https://github.com/digitalfox/pysql/tarball/master
Installing collected packages: pysql
  Running setup.py install for pysql
    Running command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-_yvnmoc2-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o7xhwhgf-record/install-record.txt --single-version-externally-managed --compile
    Warning, cannot read version file (name 'file' is not defined)
    Defaulting to 'snapshot'
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pysql
    copying src/pysql/pysqlmain.py -> build/lib/pysql
    copying src/pysql/pysqloraobjects.py -> build/lib/pysql
    copying src/pysql/pysqlcomplete.py -> build/lib/pysql
    copying src/pysql/pysqlhelpers.py -> build/lib/pysql
    copying src/pysql/pysqldb.py -> build/lib/pysql
    copying src/pysql/pysqlexception.py -> build/lib/pysql
    copying src/pysql/pysqloptionparser.py -> build/lib/pysql
    copying src/pysql/pysqlfunctions.py -> build/lib/pysql
    copying src/pysql/pysqlconf.py -> build/lib/pysql
    copying src/pysql/pysqlshell.py -> build/lib/pysql
    copying src/pysql/pysqlqueries.py -> build/lib/pysql
    copying src/pysql/pysqlaudit.py -> build/lib/pysql
    copying src/pysql/pysqlgraphics.py -> build/lib/pysql
    copying src/pysql/__init__.py -> build/lib/pysql
    copying src/pysql/pysqlcolor.py -> build/lib/pysql
    running build_scripts
    creating build/scripts-3.4
    copying and adjusting src/bin/pysql -> build/scripts-3.4
    changing mode of build/scripts-3.4/pysql from 644 to 755
    running install_lib
    creating /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlmain.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqloraobjects.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlcomplete.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlhelpers.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqldb.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlexception.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqloptionparser.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlfunctions.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlconf.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlshell.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlqueries.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlaudit.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlgraphics.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/__init__.py -> /usr/local/lib/python3.4/dist-packages/pysql
    copying build/lib/pysql/pysqlcolor.py -> /usr/local/lib/python3.4/dist-packages/pysql
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlmain.py to pysqlmain.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloraobjects.py to pysqloraobjects.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcomplete.py to pysqlcomplete.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlhelpers.py to pysqlhelpers.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqldb.py to pysqldb.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlexception.py to pysqlexception.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloptionparser.py to pysqloptionparser.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlfunctions.py to pysqlfunctions.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlconf.py to pysqlconf.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlshell.py to pysqlshell.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlqueries.py to pysqlqueries.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlaudit.py to pysqlaudit.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlgraphics.py to pysqlgraphics.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/__init__.py to __init__.cpython-34.pyc
    byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcolor.py to pysqlcolor.cpython-34.pyc
    writing byte-compilation script '/tmp/tmpmzuox7k2.py'
    /usr/bin/python3 -O /tmp/tmpmzuox7k2.py
    removing /tmp/tmpmzuox7k2.py
    running install_data
    copying src/share/locale/fr/LC_MESSAGES/pysql.mo -> /usr/local/share/locale/fr/LC_MESSAGES/
    copying version -> /usr/local/share/pysql
    copying README -> /usr/local/share/pysql
    copying ChangeLog -> /usr/local/share/pysql
    copying ChangeLog-Synthesis -> /usr/local/share/pysql
    copying LICENSE -> /usr/local/share/pysql
    running install_egg_info
    running egg_info
    creating pysql.egg-info
    writing pysql.egg-info/PKG-INFO
    writing dependency_links to pysql.egg-info/dependency_links.txt
    writing top-level names to pysql.egg-info/top_level.txt
    writing manifest file 'pysql.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pysql.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pysql.egg-info/SOURCES.txt'
    Copying pysql.egg-info to /usr/local/lib/python3.4/dist-packages/pysql-snaphot.egg-info
    running install_scripts
    copying build/scripts-3.4/pysql -> /usr/local/bin
    changing mode of /usr/local/bin/pysql to 755
    error: install_script 'pysql_w32_postinst.py' not found in scripts
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-_yvnmoc2-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o7xhwhgf-record/install-record.txt --single-version-externally-managed --compile:
    Warning, cannot read version file (name 'file' is not defined)

Defaulting to 'snapshot'

running install

running build

running build_py

creating build

creating build/lib

creating build/lib/pysql

copying src/pysql/pysqlmain.py -> build/lib/pysql

copying src/pysql/pysqloraobjects.py -> build/lib/pysql

copying src/pysql/pysqlcomplete.py -> build/lib/pysql

copying src/pysql/pysqlhelpers.py -> build/lib/pysql

copying src/pysql/pysqldb.py -> build/lib/pysql

copying src/pysql/pysqlexception.py -> build/lib/pysql

copying src/pysql/pysqloptionparser.py -> build/lib/pysql

copying src/pysql/pysqlfunctions.py -> build/lib/pysql

copying src/pysql/pysqlconf.py -> build/lib/pysql

copying src/pysql/pysqlshell.py -> build/lib/pysql

copying src/pysql/pysqlqueries.py -> build/lib/pysql

copying src/pysql/pysqlaudit.py -> build/lib/pysql

copying src/pysql/pysqlgraphics.py -> build/lib/pysql

copying src/pysql/__init__.py -> build/lib/pysql

copying src/pysql/pysqlcolor.py -> build/lib/pysql

running build_scripts

creating build/scripts-3.4

copying and adjusting src/bin/pysql -> build/scripts-3.4

changing mode of build/scripts-3.4/pysql from 644 to 755

running install_lib

creating /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlmain.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqloraobjects.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlcomplete.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlhelpers.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqldb.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlexception.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqloptionparser.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlfunctions.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlconf.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlshell.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlqueries.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlaudit.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlgraphics.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/__init__.py -> /usr/local/lib/python3.4/dist-packages/pysql

copying build/lib/pysql/pysqlcolor.py -> /usr/local/lib/python3.4/dist-packages/pysql

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlmain.py to pysqlmain.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloraobjects.py to pysqloraobjects.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcomplete.py to pysqlcomplete.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlhelpers.py to pysqlhelpers.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqldb.py to pysqldb.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlexception.py to pysqlexception.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqloptionparser.py to pysqloptionparser.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlfunctions.py to pysqlfunctions.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlconf.py to pysqlconf.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlshell.py to pysqlshell.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlqueries.py to pysqlqueries.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlaudit.py to pysqlaudit.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlgraphics.py to pysqlgraphics.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/__init__.py to __init__.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/pysql/pysqlcolor.py to pysqlcolor.cpython-34.pyc

writing byte-compilation script '/tmp/tmpmzuox7k2.py'

/usr/bin/python3 -O /tmp/tmpmzuox7k2.py

removing /tmp/tmpmzuox7k2.py

running install_data

copying src/share/locale/fr/LC_MESSAGES/pysql.mo -> /usr/local/share/locale/fr/LC_MESSAGES/

copying version -> /usr/local/share/pysql

copying README -> /usr/local/share/pysql

copying ChangeLog -> /usr/local/share/pysql

copying ChangeLog-Synthesis -> /usr/local/share/pysql

copying LICENSE -> /usr/local/share/pysql

running install_egg_info

running egg_info

creating pysql.egg-info

writing pysql.egg-info/PKG-INFO

writing dependency_links to pysql.egg-info/dependency_links.txt

writing top-level names to pysql.egg-info/top_level.txt

writing manifest file 'pysql.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



reading manifest file 'pysql.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'pysql.egg-info/SOURCES.txt'

Copying pysql.egg-info to /usr/local/lib/python3.4/dist-packages/pysql-snaphot.egg-info

running install_scripts

copying build/scripts-3.4/pysql -> /usr/local/bin

changing mode of /usr/local/bin/pysql to 755

error: install_script 'pysql_w32_postinst.py' not found in scripts

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-_yvnmoc2-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o7xhwhgf-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-_yvnmoc2-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-_yvnmoc2-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o7xhwhgf-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-_yvnmoc2-build
```

Again thank you very much for your help
